### ISSUE TITLE
[Bug] Interface Glitch with Certain Plugins

### ISSUE THREAD

**Issue by luxlogica** [mludowise/Sketch-Plugin-Manager#13]
It seems that there are some interface glitches when displaying the list of plugins - and that the glitch always appears, consistently, on the same plugin entries. For instance, when listing all plugins alphabetically, scrolling down a little we get to...:

<img width="774" alt="screen shot 2017-05-06 at 1 42 07 pm" src="https://cloud.githubusercontent.com/assets/2994472/25769613/f013c6d6-3261-11e7-9d38-46855723a9be.png">

**Comment by mludowise** [comment]
Can you please include what version of OS X you're using (e.g. 10.12.4)? To find the version number, go to the Apple menu -> About This Mac.

**Comment by luxlogica** [comment]
Using the very latest MacOS X Sierra - 10.12.4 (and the latest version of Sketch - 43.2).

**Comment by mludowise** [comment]
I'm on the same version of OS X and Sketch, but I'm unable to reproduce the bug 🤔

I'd like to take a look at the logs to see if there's anything in there. Here's what I'd like you to do:
  1. Launch the **Console** application _(under /Applications/Utilities/Console.app)_.
  2. Click the leftmost button in the toolbar to show the sidebar, if it’s hidden.
  3. Select **All Messages** in the tab bar.
  4. If the **Activities** button in the toolbar is enabled with a blue icon, click it to turn this off.
  5. In the search bar, type **Sketch** and hit return.
  6. In the search bar, change the dropdown from **Any** to **Process**. _The console should look similar to the image below at this point._
  7. Switch back to **Sketch**, open the **Sketch Plugin Manager**, and reproduce the bug.
  8. Return to the Console, and select one of the messages from the main window.
  9. From the Menu Bar choose **Edit ▸ Select All**.
  10. From the Menu Bar, choose **Edit ▸ Copy**. Then, open the TextEdit application and Paste the copied logs into a new plain text document.
  11. **Save** the text document in _.txt_ format, and attach this to this report.

![image](https://cloud.githubusercontent.com/assets/1626168/25776734/1604652a-327c-11e7-8d70-061a2e5435a6.png)

**Comment by mludowise** [comment]
I just pushed an update that fixed some minor bugs. It's possible that they may fix this UI glitch as well. Could you please update the plugin, restart Sketch, and see if you can reproduce the issue?

Thank you.

**Comment by luxlogica** [comment]
@mludowise: thank you for your quick response. I updated the plugin, restarted Sketch, and ran into a horrible crashing bug - #15...

**Comment by luxlogica** [comment]
The 'crash-fix' branch seems to have fixed this! 

<img width="776" alt="screen shot 2017-05-09 at 8 24 25 am" src="https://cloud.githubusercontent.com/assets/2994472/25828009/4f195b56-3491-11e7-98e2-fecce102856b.png">

**Comment by mludowise** [comment]
Fixed.
