### ISSUE TITLE
[BUG] Conflicts with "Abstract" plugin

### ISSUE THREAD

**Issue by kenrossi** [mludowise/Sketch-Plugin-Manager#16]
I can't seem to get past this screen. 
![screenshot 2017-05-17 12 07 24](https://cloud.githubusercontent.com/assets/9726867/26164101/a38a7968-3af9-11e7-9dae-2829c81d842f.PNG)

**Comment by mludowise** [comment]
Can you please include what version of OS X you're using (e.g. 10.12.4)? To find the version number, go to the Apple menu -> About This Mac.

Could I also get a copy of your Sketch logs. [Here are instructions on how to export logs from Sketch](https://github.com/mludowise/Sketch-Plugin-Manager/wiki/Exporting-Logs).

What happens when you click "View Updates"? From the screenshot, it looks like the "Update Plugins" alert never goes away and obscures the window behind it. Or does it keep popping up repeatedly?

**Comment by mludowise** [comment]
Also, could you please tell me what language and region your system is configured (e.g. English, US).

**Comment by kenrossi** [comment]
10.12.3  

View updates pops up like 3 times.. I click view all then it crashes. I have also dismissed it a bunch of times and then click update all and it crashes. 

[error_sketch.txt](https://github.com/mludowise/Sketch-Plugin-Manager/files/1008750/error_sketch.txt)

**Comment by kenrossi** [comment]
![screenshot 2017-05-17 14 11 34](https://cloud.githubusercontent.com/assets/9726867/26170008/d55bdbbc-3b0d-11e7-9a59-037250a7efed.PNG)

It shows that sketch plugin manager needs an update even though it is the latest version.

**Comment by mludowise** [comment]
From the logs, I think I'm able to track down what's causing the crash which may also be causing the error where the alert isn't dismissing.

It looks like an older version of one of the libraries that SPM depends on, ObjectiveGit, is being used by another plugin that you have installed. The newer version of ObjectiveGit is never loaded by SPM so when the plugin tries to use it, it crashes.

I looked at all of the plugins in your screenshot of the Updates tab and none of them are using ObjectiveGit. Do you have any other plugins installed that might be doing anything related to Git? If so, it's likely that it's conflicting with SPM.

**Comment by kenrossi** [comment]
I just pinged the developers of Abstract. It's actually a Git based plugin. 

![screenshot 2017-05-17 15 16 54](https://cloud.githubusercontent.com/assets/9726867/26171697/eed38e54-3b13-11e7-91e9-4af15da1a0b8.PNG)

**Comment by mludowise** [comment]
Ah, that's likely it then.

For the time being you should uninstall either SPM or Abstract. I'm going to look into ways of loading libraries that won't conflict with other plugins, but it may take a while before I can get a fix for this. I'll leave this bug open and let you know if and when I have a fix.

**Comment by mludowise** [comment]
This should be fixed now.
