### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by mludowise** [mludowise/Sketch-Plugin-Manager#25]
Based on app analytics, more than half of Sketch Plugin Manager's users primary language is Chinese (specifically zh-Hans-CN). I'd like help from someone fluent in Chinese to help translate to simplified and possibly also traditional Chinese.

I've posted instructions how to contribute:
https://github.com/mludowise/Sketch-Plugin-Manager/tree/localize

**Comment by mludowise** [comment]
@cute @pluwen – You've both made contributions to the [SketchI18N](https://github.com/cute/SketchI18N) plugin, would you be interested in helping translate Sketch Plugin Manager?

**Comment by pluwen** [comment]
@mludowise I'm in!

**Comment by pluwen** [comment]
@mludowise Done. https://github.com/mludowise/Sketch-Plugin-Manager/pull/26

**Comment by mludowise** [comment]
Thank you! I'll integrate this into the plugin.

**Comment by mludowise** [comment]
I integrated the localization into the plugin. You should see the change if you update in Sketch Plugin Manager and your system has Chinese (Simplified) as one of the preferred languages.

Please let me know if you see any problems.

**Comment by pluwen** [comment]
Why not use UTF-8 ？Sent from Nylas Mail, the best free email app for work
          
            
            On 6月 15 2017, at 11:09 上午, Mel Ludowise <notifications@github.com> wrote:
            
            
              I integrated the localization into the plugin. You should see the change if you update in Sketch Plugin Manager and your system has Chinese (Simplified) as one of the preferred languages.
Please let me know if you see any problems.

**Comment by pluwen** [comment]
Change some strings
https://github.com/mludowise/Sketch-Plugin-Manager/pull/28

**Comment by mludowise** [comment]
Thank you. I'll include the fixes in the next update.

Regarding your comment on UTF-8, I believe the Localizable.strings file is already in UTF-8, is it not?

**Comment by pluwen** [comment]
no, it's UTF-16LE

**Comment by mludowise** [comment]
@pluwen Ah, yes. It looks like Apple wants the Localizable.strings files to be in UTF-16. When I import them into XCode, it automatically converts them from UTF-8 to UTF-16.

**Comment by pluwen** [comment]
ok
