### ISSUE TITLE
[Bug] Crashes when typing into search box immediately after opening manager

### ISSUE THREAD

**Issue by mludowise** [mludowise/Sketch-Plugin-Manager#31]
### Description
[//]: # (Include a detailed description of the problem)
1. Open the manager
2. Immediately after the window displays, type into the search box "test"

### OS X Version
[//]: # (e.g. 10.12.4; To find the version number, go to the Apple menu -> About This Mac.)
10.12.5

### Sketch Plugin Manager Version
[//]: # (To find the version number, in Sketch go to Preferences > Plugins and look for the gray number next to "Sketch Plugin Manager".)
1.6

### Screenshot
[//]: # (Include a screenshot or screen recording, if applicable)
N/A

### Logs
[//]: # (Attach a .txt file containing logs for Sketch Plugin Manager. For instructions on how to export logs:)
[//]: # (For v1.4+: https://github.com/mludowise/Sketch-Plugin-Manager/wiki/Exporting-Logs-v1.4-or-higher)
[//]: # (For v1.3 or lower: https://github.com/mludowise/Sketch-Plugin-Manager/wiki/Exporting-Logs---v1.3-or-lower)
Crash Report:
[Sketch Plugin Manager_2017-06-20-182209_Jingidy.crash.zip](https://github.com/mludowise/Sketch-Plugin-Manager/files/1092839/Sketch.Plugin.Manager_2017-06-20-182209_Jingidy.crash.zip)

**Comment by muenva** [comment]
It happens when I open an existing file, if I open a new document then it doesn't crash. @mludowise Do you have the same results?
Tested with same plugin manager version but with OS X v10.12.6

**Comment by mludowise** [comment]
I know the root cause of the bug, but haven't had the time to figure out exactly how to fix it. The one that I'm running into is a race condition where, if you type in the search box before the plugins list finishes updating in the background, it crashes.

When you open the new document, are you seeing a popup that notifies you of updated plugins? If so, that's probably why it's not crashing for you when opening a new document. The popup opens after it's done loading the list of plugins.

**Comment by muenva** [comment]
Thanks for the quick response! I see now. I don't get the popup but I managed to replicate the bug when creating new documents.

**Comment by mludowise** [comment]
This should be fixed now.
