### ISSUE TITLE
App will not launch

### ISSUE THREAD

**Issue by bsmart** [mludowise/Sketch-Plugin-Manager#32]
### Description

App will not launch from Plugins > Sketch Plugin Manager

### OS X Version

10.12.5

### Sketch Plugin Manager Version

1.6

### Screenshot

[//]: # (Include a screenshot or screen recording, if applicable)

### Logs

[//]: # (Attach a .txt file containing logs for Sketch Plugin Manager. For instructions on how to export logs:)
[//]: # (For v1.4+: https://github.com/mludowise/Sketch-Plugin-Manager/wiki/Exporting-Logs-v1.4-or-higher)
[//]: # (For v1.3 or lower: https://github.com/mludowise/Sketch-Plugin-Manager/wiki/Exporting-Logs---v1.3-or-lower)

**Comment by mludowise** [comment]
I have a few followup questions:
1. Are you selecting `Plugins > Sketch Plugin Manager > Open Manager` from the menu?
2. Have you been able to launch Sketch Plugin Manager before?

If you've selected `Open Manager` from the menu and nothing happens, can you please check to see if it's running in the background using the **Activity Monitor** app? To do this:
- Open `Activity Monitor.app` located in the `/Applications/Utilities/` folder
- Type **"sketch"** in the search bar in the upper right
- Check to see if there is a process name called **"Sketch Plugin Manager"** listed. If there is, select it and click the 🛑 icon in the upper left to stop the process.
![image](https://user-images.githubusercontent.com/1626168/28385677-d6c86bb8-6c7d-11e7-8ff4-efd2c0b861ac.png)

Let me know if you're able to see the process in Activity Monitor.

**Comment by bsmart** [comment]
1. I ran `Plugins > Sketch Plugin Manager > Open Manager` from the menu and nothing happened.
2. Sketch PLugin Manager was not running when I checked activity monitor.
3. I uninstalled and redownloaded Sketch Plugin Manager and reinstalled. Now the plugin manager works and I was able to install a plugin.

**Comment by mludowise** [comment]
That's great to hear. I'm going to close this for now but please feel free to reopen if you run into the same problem again.
