### ISSUE TITLE
Not available for use

### ISSUE THREAD

**Issue by andrewux** [mludowise/Sketch-Plugin-Manager#33]
### Description

Installed Sketch Plugin Manage from fresh download. Installation went well - appeared to be successful. Opening the Sketch Plugin Manager menu reveals all options disabled.

### OS X Version

10.12.5

### Sketch Plugin Manager Version

1.6

### Screenshot

![image](https://user-images.githubusercontent.com/6595680/28357518-9785a476-6c63-11e7-8895-e56683080a7b.png)

### Logs

No Log available

**Comment by mludowise** [comment]
In that screenshot, do you have a document open? Sketch disables all plugins unless you have an active document window.

**Comment by mludowise** [comment]
I'm closing this issue. Please reopen if you run into this problem again.
