### ISSUE TITLE
Catalog tab not showing plugins

### ISSUE THREAD

**Issue by fali292** [mludowise/Sketch-Plugin-Manager#36]
### Description

I cannot browse or search for plugins using the catalog tab in sketch plugin manager. I'm able to install plugins via sketchpacks and they show up on sketch plugin managers installed section but aren't updatable 

### OS X Version

10.12.6

### Sketch Plugin Manager Version

1.6

### Screenshot
![screen shot 2017-10-03 at 16 10 50](https://user-images.githubusercontent.com/26438096/31133373-2fd3c242-a857-11e7-95ce-3d291949cc24.png)

### Logs

default	16:16:43.489429 +0100	Sketch Plugin Manager	TIC TCP Conn Cancel [1:0x611000018780]
default	16:16:43.489627 +0100	Sketch Plugin Manager	TIC TCP Conn Destroyed [1:0x611000018780]
default	16:17:46.489154 +0100	Sketch Plugin Manager	pluginDirectory: Optional("/Users/Fahim/Library/Application Support/com.bohemiancoding.sketch3/Plugins")
default	16:17:46.489715 +0100	Sketch Plugin Manager	pluginFile: Optional("/Users/Fahim/Library/Application Support/com.bohemiancoding.sketch3/Plugins/sketch-plugin-manager.sketchplugin")
default	16:17:46.490026 +0100	Sketch Plugin Manager	checkForUpdates: false
default	16:17:46.490246 +0100	Sketch Plugin Manager	alwaysShowUpdateAlert: false
default	16:17:46.490503 +0100	Sketch Plugin Manager	autoReinstall: true
default	16:17:46.509309 +0100	Sketch Plugin Manager	0x60600009a1c0 opened /var/folders/yf/45zsh79x4_s80tkbpy0vy_sw0000gn/C//mds/mdsObject.db: 4636 bytes
default	16:17:46.510833 +0100	Sketch Plugin Manager	0x606000095840 opened /var/folders/yf/45zsh79x4_s80tkbpy0vy_sw0000gn/C//mds/mdsDirectory.db: 50744 bytes
default	16:17:46.513415 +0100	Sketch Plugin Manager	Using your own bundle identifier as an NSUserDefaults suite name does not make sense and will not work. Break on _NSUserDefaults_Log_Nonsensical_Suites to find this
default	16:17:46.519687 +0100	Sketch Plugin Manager	0x6060000ac7c0 opened /var/folders/yf/45zsh79x4_s80tkbpy0vy_sw0000gn/C//mds/mdsDirectory.db: 50744 bytes
default	16:17:46.528686 +0100	Sketch Plugin Manager	0x6060000b9060 opened /Users/Fahim/Library/Keychains/login.keychain-db: 273712 bytes
default	16:17:46.540927 +0100	Sketch Plugin Manager	0x6060000c4820 opened /Library/Keychains/System.keychain: 33692 bytes
default	16:17:46.554275 +0100	Sketch Plugin Manager	TIC TCP Conn Start [1:0x61100001c240]
default	16:17:46.601727 +0100	Sketch Plugin Manager	TIC TCP Conn Event [1:0x61100001c240]: 1 Err(0)
default	16:17:46.601838 +0100	Sketch Plugin Manager	TIC TCP Conn Connected [1:0x61100001c240]: Err(0)
default	16:17:46.602124 +0100	Sketch Plugin Manager	TIC Enabling TLS [1:0x61100001c240]
default	16:17:46.626229 +0100	Sketch Plugin Manager	TIC TLS Event [1:0x61100001c240]: 2, Pending(0)
default	16:17:46.627666 +0100	Sketch Plugin Manager	TIC TLS Event [1:0x61100001c240]: 11, Pending(0)
default	16:17:46.629738 +0100	Sketch Plugin Manager	TIC TLS Event [1:0x61100001c240]: 12, Pending(0)
default	16:17:46.629898 +0100	Sketch Plugin Manager	TIC TLS Event [1:0x61100001c240]: 14, Pending(0)
default	16:17:46.637325 +0100	Sketch Plugin Manager	TIC TLS Trust Result [1:0x61100001c240]: 0
default	16:17:46.663725 +0100	Sketch Plugin Manager	TIC TLS Event [1:0x61100001c240]: 20, Pending(0)
default	16:17:46.664757 +0100	Sketch Plugin Manager	TIC TCP Conn Event [1:0x61100001c240]: 8 Err(0)
default	16:17:46.664853 +0100	Sketch Plugin Manager	TIC TLS Handshake Complete [1:0x61100001c240]
default	16:17:46.893050 +0100	Sketch Plugin Manager	Faulting in NSHTTPCookieStorage singleton
default	16:17:46.893150 +0100	Sketch Plugin Manager	Faulting in CFHTTPCookieStorage singleton
default	16:17:46.893260 +0100	Sketch Plugin Manager	Creating default cookie storage with process/bundle identifier
default	16:17:46.898056 +0100	Sketch Plugin Manager	TIC TCP Conn Start [2:0x61100006f580]
default	16:17:46.969425 +0100	Sketch Plugin Manager	Looking for plugins in path: /Users/Fahim/Library/Application Support/com.bohemiancoding.sketch3/Plugins
default	16:17:46.970741 +0100	Sketch Plugin Manager	Found file: Adjust Button Shape.sketchplugin
default	16:17:46.974598 +0100	Sketch Plugin Manager	Found file: getflourish-Sketch-Mate-fa0f20a
default	16:17:46.977868 +0100	Sketch Plugin Manager	Found file: kenmoore-sketch-relabel-button-d743d9f
default	16:17:46.981832 +0100	Sketch Plugin Manager	Found file: Panels.sketchplugin
default	16:17:46.994996 +0100	Sketch Plugin Manager	Found file: PEZ-SketchDistributor-5542359
default	16:17:46.997362 +0100	Sketch Plugin Manager	Found file: sketch-palettes-2.12
default	16:17:46.999420 +0100	Sketch Plugin Manager	Found file: sketch-plugin-manager.sketchplugin
default	16:17:47.006740 +0100	Sketch Plugin Manager	Found file: Unsplash-It-Sketch-1.5
error	16:18:46.893319 +0100	Sketch Plugin Manager	NSURLSessionTask finished with error - code: -1001
default	16:18:46.894702 +0100	Sketch Plugin Manager	TIC TCP Conn Cancel [2:0x61100006f580]
error	16:18:46.895270 +0100	Sketch Plugin Manager	HTTP load failed (error code: -999 [1:89])
default	16:18:46.895341 +0100	Sketch Plugin Manager	Error: The request timed out.
default	16:18:46.895605 +0100	Sketch Plugin Manager	Error occurred downloading catalog
default	16:19:02.100382 +0100	Sketch Plugin Manager	pluginDirectory: Optional("/Users/Fahim/Library/Application Support/com.bohemiancoding.sketch3/Plugins")
default	16:19:02.100748 +0100	Sketch Plugin Manager	pluginFile: Optional("/Users/Fahim/Library/Application Support/com.bohemiancoding.sketch3/Plugins/sketch-plugin-manager.sketchplugin")
default	16:19:02.100995 +0100	Sketch Plugin Manager	checkForUpdates: false
default	16:19:02.101194 +0100	Sketch Plugin Manager	alwaysShowUpdateAlert: false
default	16:19:02.101408 +0100	Sketch Plugin Manager	autoReinstall: true
default	16:19:02.118211 +0100	Sketch Plugin Manager	0x60600007ff40 opened /var/folders/yf/45zsh79x4_s80tkbpy0vy_sw0000gn/C//mds/mdsObject.db: 4636 bytes
default	16:19:02.119298 +0100	Sketch Plugin Manager	Using your own bundle identifier as an NSUserDefaults suite name does not make sense and will not work. Break on _NSUserDefaults_Log_Nonsensical_Suites to find this
default	16:19:02.119824 +0100	Sketch Plugin Manager	0x60600009b540 opened /var/folders/yf/45zsh79x4_s80tkbpy0vy_sw0000gn/C//mds/mdsDirectory.db: 50744 bytes
default	16:19:02.128606 +0100	Sketch Plugin Manager	0x60600008f6c0 opened /var/folders/yf/45zsh79x4_s80tkbpy0vy_sw0000gn/C//mds/mdsDirectory.db: 50744 bytes
default	16:19:02.137489 +0100	Sketch Plugin Manager	0x6060000bbee0 opened /Users/Fahim/Library/Keychains/login.keychain-db: 273712 bytes
default	16:19:02.149841 +0100	Sketch Plugin Manager	0x6060000ca520 opened /Library/Keychains/System.keychain: 33692 bytes
default	16:19:02.162872 +0100	Sketch Plugin Manager	TIC TCP Conn Start [1:0x611000039340]
default	16:19:02.229962 +0100	Sketch Plugin Manager	TIC TCP Conn Event [1:0x611000039340]: 1 Err(0)
default	16:19:02.230076 +0100	Sketch Plugin Manager	TIC TCP Conn Connected [1:0x611000039340]: Err(0)
default	16:19:02.230415 +0100	Sketch Plugin Manager	TIC Enabling TLS [1:0x611000039340]
default	16:19:02.253983 +0100	Sketch Plugin Manager	TIC TLS Event [1:0x611000039340]: 2, Pending(0)
default	16:19:02.255706 +0100	Sketch Plugin Manager	TIC TLS Event [1:0x611000039340]: 11, Pending(0)
default	16:19:02.257638 +0100	Sketch Plugin Manager	TIC TLS Event [1:0x611000039340]: 12, Pending(0)
default	16:19:02.257740 +0100	Sketch Plugin Manager	TIC TLS Event [1:0x611000039340]: 14, Pending(0)
default	16:19:02.265217 +0100	Sketch Plugin Manager	TIC TLS Trust Result [1:0x611000039340]: 0
default	16:19:02.291767 +0100	Sketch Plugin Manager	TIC TLS Event [1:0x611000039340]: 20, Pending(0)
default	16:19:02.292844 +0100	Sketch Plugin Manager	TIC TCP Conn Event [1:0x611000039340]: 8 Err(0)
default	16:19:02.292943 +0100	Sketch Plugin Manager	TIC TLS Handshake Complete [1:0x611000039340]
default	16:19:02.489025 +0100	Sketch Plugin Manager	Faulting in NSHTTPCookieStorage singleton
default	16:19:02.489126 +0100	Sketch Plugin Manager	Faulting in CFHTTPCookieStorage singleton
default	16:19:02.489225 +0100	Sketch Plugin Manager	Creating default cookie storage with process/bundle identifier
default	16:19:02.493998 +0100	Sketch Plugin Manager	TIC TCP Conn Start [2:0x611000013640]
default	16:19:02.513756 +0100	Sketch Plugin Manager	Looking for plugins in path: /Users/Fahim/Library/Application Support/com.bohemiancoding.sketch3/Plugins
default	16:19:02.514643 +0100	Sketch Plugin Manager	Found file: Adjust Button Shape.sketchplugin
default	16:19:02.519020 +0100	Sketch Plugin Manager	Found file: getflourish-Sketch-Mate-fa0f20a
default	16:19:02.522658 +0100	Sketch Plugin Manager	Found file: kenmoore-sketch-relabel-button-d743d9f
default	16:19:02.524898 +0100	Sketch Plugin Manager	Found file: Panels.sketchplugin
default	16:19:02.537675 +0100	Sketch Plugin Manager	Found file: PEZ-SketchDistributor-5542359
default	16:19:02.540125 +0100	Sketch Plugin Manager	Found file: sketch-palettes-2.12
default	16:19:02.542069 +0100	Sketch Plugin Manager	Found file: sketch-plugin-manager.sketchplugin
default	16:19:02.607015 +0100	Sketch Plugin Manager	Found file: Unsplash-It-Sketch-1.5

**Comment by mludowise** [comment]
Thank you for reporting this. My computer is currently out of commission, but I will try to look at this in a week when I get it back.

**Comment by mludowise** [comment]
I've finally had a chance to come back to this project. Are you still having the same problem with not showing a catalog?

**Comment by fali292** [comment]
Hi,

No, fortunately the catalog is visible now and has been a few days after my last message. I don’t recall doing anything to make it work such as uninstalling and reinstalling if that helps.

Thanks
