### ISSUE TITLE
Closes after a few seconds when first opened

### ISSUE THREAD

**Issue by cpshanley** [mludowise/Sketch-Plugin-Manager#37]
### Description

This has been happening for the last few versions of Sketch and the plugin.

When you first open the window, it dismisses after about 5 seconds. Open it again, and it stays on the screen.

### OS X Version
10.12.6

### Sketch Plugin Manager Version
1.6

**Comment by casper-eisma** [comment]
Same here on OS X 10.13.1

**Comment by pjatx** [comment]
Same on OS X 10.13.1

**Comment by mludowise** [comment]
I've finally had a chance to work on this and I think I'll have a fix in the next release. Thank you for catching this.

**Comment by mludowise** [comment]
This should be fixed now. Please let me know if any of you run into this problem again.

**Comment by parkerault** [comment]
I've been having this issue so badly it's unusable; I've attached a screen recording (gif) of it crashing four times in a row. Sometimes it will crash with no user input, but it _always_ crashes when I try to open the installed or update tabs. System: OSX 10.12.6, Sketch v47.1 (update license expired), and Sketch Plugin Manager v1.6. Is there somewhere I should look for a log to attach?

![sketch-plugin-manager-crashing](https://user-images.githubusercontent.com/78856/36287395-2acb085e-127a-11e8-94c0-6115bcd14331.gif)

**Comment by mludowise** [comment]
@parkerault This bug has been fixed in version 1.7.

It looks like this bug is preventing the plugin from being able to update itself, but you can fix it by downloading it from GitHub and reinstalling it.

Please let me know if you run into any more problems.
