### ISSUE TITLE
Minor spelling error in github description

### ISSUE THREAD

**Issue by howdytom** [mludowise/Sketch-Plugin-Manager#40]
### Description

I just want to let you know that there's a spelling error in the github description:

Sketch Plugin Manager is currently only supported on OS X 10.12 S**ei**rra…

Correct would be "OS X 10.12 **Sierra**“ or macOS 10.12 **Sierra**. 

By the way, great work!

**Comment by mludowise** [comment]
How embarrassing 🤭

Thank you for pointing that out, I’ll fix it right away.

- Mel
________________________________

**Comment by howdytom** [comment]
Nice. Same mixup on the landing page

[https://mludowise.github.io/Sketch-Plugin-Manager/](https://mludowise.github.io/Sketch-Plugin-Manager/)

**Comment by mludowise** [comment]
Should be fixed now.
